name: Python CI

on:
  push:                # Kích hoạt khi có lệnh `git push`
    branches:
      - master           # Chạy trên nhánh `main`
      - init_tests     # Chạy trên nhánh `init_tests`
      - van
  pull_request:        # Kích hoạt khi tạo pull request
    branches:
      - master           # Kích hoạt khi tạo pull request vào nhánh `main`
      - init_tests
      - van
jobs:
  test:
    runs-on: ubuntu-latest   # Chạy trên môi trường Ubuntu

    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Sử dụng Python phiên bản 3.9

      # Bước 3: Cài đặt dependencies từ requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Bước 4: Chạy kiểm tra với pytest
      - name: Run tests
        run: |
          pytest tests/test_model.py
