name: Python CI with Training Check

on:
  push:
    branches:
      - main
      - init_tests
      - van
      - training_loging
  pull_request:
    branches:
      - main
      - init_tests
      - van
      - training_loging

jobs:
  test-and-train:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Bước 4: Chạy kiểm tra (test)
      - name: Run tests
        run: |
          pytest tests/test_model.py